export const types = {
    GETALLITEMS: 'GETALLITEMS',
    LOGIN: 'LOGIN',
    REGISTER: 'REGISTER',
    LOGOUT: 'LOGOUT',
    SELECTECATE: 'SELECTECATE',
    GETITEM: 'GETITEM',
    GETAUCTIONERS: 'GETAUCTIONERS',
    PLACEBID: 'PLACEBID',
    AUTHEN: 'AUTHEN',
    GETSAMECATEITEMS: 'GETSAMECATEITEMS',
    SHOWLOGIN: 'SHOWLOGIN',
    CLOSELOGIN: 'CLOSELOGIN',
    LOADING: 'LOADING',
    LOADED: 'LOADED',
    SHOWFILTER: 'SHOWFILTER',
    HIDEFILTER: 'HIDEFILTER',
    AUTOUPDATE: 'AUTOUPDATE'
}